<?xml version="1.0" encoding="UTF-8"?><testsuite errors="1" failures="1" name="com.studentapp.junit.studentsidinfo.SecondSerenityTest" skipped="4" tests="8" time="8.07" timestamp="2019-06-154 11:17:41"><testcase classname="com.studentapp.junit.studentsidinfo.SecondSerenityTest" name="This is a skipped test"><skipped/></testcase><testcase classname="com.studentapp.junit.studentsidinfo.SecondSerenityTest" name="This is atest with error"><error message="/ by zero" type="java.lang.ArithmeticException">/ by zero</error><system-err>/ by zero&#13;
com.studentapp.junit.studentsidinfo.SecondSerenityTest.thisIsAtestWithError(SecondSerenityTest.java:62)&#13;
</system-err></testcase><testcase classname="com.studentapp.junit.studentsidinfo.SecondSerenityTest" name="This test will get the information of all the students from the Student App"/><testcase classname="com.studentapp.junit.studentsidinfo.SecondSerenityTest" name="This is a pending test"><skipped/></testcase><testcase classname="com.studentapp.junit.studentsidinfo.SecondSerenityTest" name="This is a manual test"><skipped/></testcase><testcase classname="com.studentapp.junit.studentsidinfo.SecondSerenityTest" name="This isa failing"><failure message="1 expectation failed.&#10;Expected status code &lt;500&gt; but was &lt;200&gt;.&#10;" type="java.lang.AssertionError">1 expectation failed.
Expected status code &lt;500&gt; but was &lt;200&gt;.
</failure><system-err>1 expectation failed.
Expected status code &lt;500&gt; but was &lt;200&gt;.
&#13;
io.restassured.internal.ResponseSpecificationImpl.validateResponseIfRequired(ResponseSpecificationImpl.groovy:636)&#13;
io.restassured.internal.ResponseSpecificationImpl.statusCode(ResponseSpecificationImpl.groovy:122)&#13;
io.restassured.internal.ResponseSpecificationImpl.statusCode(ResponseSpecificationImpl.groovy:130)&#13;
io.restassured.internal.ValidatableResponseOptionsImpl.statusCode(ValidatableResponseOptionsImpl.java:117)&#13;
com.studentapp.junit.studentsidinfo.SecondSerenityTest.thisIsaFailing(SecondSerenityTest.java:44)&#13;
</system-err></testcase><testcase classname="com.studentapp.junit.studentsidinfo.SecondSerenityTest" name="File does not exist"><compromised message="E:\file.txt (The device is not ready)" type="java.io.FileNotFoundException">E:\file.txt (The device is not ready)</compromised><system-err>E:\file.txt (The device is not ready)&#13;
com.studentapp.junit.studentsidinfo.SecondSerenityTest.fileDoesNotExist(SecondSerenityTest.java:69)&#13;
</system-err></testcase><testcase classname="com.studentapp.junit.studentsidinfo.SecondSerenityTest" name="Get all students"/></testsuite>